et: 1.0
delta: 2.0
delta0: 3.0
dz: 4.0
dzshort: 5.0
dz2: 6.0
ttodz: 7.0
ztof: 8.0
eta: 9.0
dg: 10.0
dg2: 11.0
dg3: 12.0
gtoz: 13.0
gtot: 14.0
gtof: 15.0
gtoeta: 16.0
sp: 17.0
sampledz: 18.0
sampledg: 19.0
samplettoz: 20.0
samplettog: 21.0
zfromr: 22.0
gfromr: 23.0
noncent2: 24.0
noncentk: 25.0
noncentdata: 26.0
noncentdz: 27.0
noncentdg: 28.0
noncentdw: 29.0
noncentf: 30.0
noncentt: 31.0
ci: 32.0
power: 33.0
cipowerdg: 34.0
cipowerdg2: 35.0
