---
class       : "draft"
title       : "Standardized means difference effect size measures for planned comparisons, trend analysis and other applications of contrast analysis"
shorttitle   : "Effect sizes measures for contrasts"
author       : "Marcello Gallucci"
address1     : "Piazza dell'Ateneo Nuovo,"
address2     : "20126 Milan, Italy"
phone        : "+39-3406841499"
email        :  "marcello.gallucci\\@unimib.it"
department   : "Department of Psychology"
jname        : Psychological Methods
jeditor      : Lisa L. Harlow, PhD
jdepartment  : Department of Psychology
jistitution  : University of Rhode Island
jaddress1    : 10 Chafee Rd, Suite 8
jaddress2    : Kingston, RI 02881-0808
output:
  pdf_document:
    template: resources/cover_letter_5.tex
    
---

together with my co-author Marco Perugini, we are pleased to submit our paper _"`r rmarkdown::metadata$title`"_ to _`r rmarkdown::metadata$jname`_. The manuscript presents a thorough examination of effect size indexes for contrast analysis that can be used and interpreted like the Cohen's d effect size measure. To the best of our knowledge, this issue has not been covered by the relevant literature as much as it deserves. The manuscript outlines formal definitions of different effect size indexes, discusses advantages and disadvantages of each, and provides practical examples of computation and applications. The effect size indexes are discussed in the context of original research, power analysis, accuracy evaluation, and meta-analysis. A R package meant to simplify the computation of the effect size indexes in contrast analysis is also presented. We hope that the topic we cover and the results we describe may be interesting for the _`r rmarkdown::metadata$jname`_ redearship.

In preparing this manuscript we were inspired by the idea of sharing our material as much as possible with the reviewers and the potential readership. With this in mind, we have prepared several pieces of material that can be accessed by the Editor and the reviewers. As regard the manuscript, the material is available at [github page](https://github.com/mcfanda/smdeffectsizepaper)[^surenote]:

* The source of the manuscript in Rmarkdown, with embedded data and examples developed in the paper.

* An accompany document with all the algebraic derivations of the formulas in the manuscript. They are indeed simple algebraic manipulations of the effect size indexes, but we feel that adding them as an appendix to the paper would result in a tedious burden for the reader, whereas sharing them on a separate document may help the reviewers checking the quality of our results.  

As regard the accompanying software, a R package named `cpower` can be downloaded from [github cpower page](https://github.com/mcfanda/cpower)[^surenote2]


Finaly, we would like to unsure you that the manuscript is not under review elsewhere, that any primary data have not been published previously or accepted for publication, and that the appropriate ethical guidelines were followed in the conduct of the research.


\setlength{\leftskip}{0.4in}
\setlength{\parindent}{-0.4in}

[^surenote]: https://github.com/mcfanda/smdeffectsizepaper
[^surenote2]: https://github.com/mcfanda/cpower